[project]
name = "wlt"
version = "0.1.0"
description = "Flask interface for managing nftables-based network access"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.1.1",
    "pyyaml>=6.0,<7",
    "pydantic==2.9.2",
]


